### ISSUE TITLE
Get express and front-end deployment to work on Heeba's machine

### ISSUE THREAD

**Issue by hjkaria** [CSE442-SPEAK/speak#53]
- `react-scripts` keeps failing after running `npm start`:
```
> speak-frontend@0.1.0 start /home/heeborum/Desktop/School/CSE442/speak/speak-frontend
> react-scripts start

/home/heeborum/Desktop/School/CSE442/speak/speak-frontend/node_modules/react-scripts/scripts/start.js:33
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

npm ERR! Linux 4.10.0-35-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! speak-frontend@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the speak-frontend@0.1.0 start script 'react-scripts start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the speak-frontend package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     react-scripts start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs speak-frontend
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls speak-frontend
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/heeborum/Desktop/School/CSE442/speak/speak-frontend/npm-debug.log
```

**Comment by wenxuans** [comment]
:(

**Comment by hjkaria** [comment]
SOLUTION: https://stackoverflow.com/questions/10075990/upgrading-node-js-to-latest-version

Updated `Node` to `v6.11.3`
